#! /bin/bash

configroot=/kroot/rel/default
instrument=lris2
component=`basename $0`

# Make sure that if envvar's KROOT and RELDIR are set, they are correct:
. /kroot/rel/default/etc/init.d/enforceRootEnv

# Source the generic lickSysV script:
. $RELDIR/etc/init.d/lickSysV
